/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TowelType = IDL.Variant({
  'bath' : IDL.Null,
  'face' : IDL.Null,
  'hand' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DispatchEntry = IDL.Record({
  'id' : IDL.Nat64,
  'destination' : IDL.Text,
  'date' : IDL.Text,
  'towelType' : TowelType,
  'quantityMeters' : IDL.Float64,
  'notes' : IDL.Text,
  'adminId' : IDL.Principal,
});
export const ProductionEntry = IDL.Record({
  'id' : IDL.Nat64,
  'workerId' : IDL.Principal,
  'date' : IDL.Text,
  'towelType' : TowelType,
  'quantityMeters' : IDL.Float64,
  'notes' : IDL.Text,
  'workerName' : IDL.Text,
});
export const Stock = IDL.Record({
  'bathTowels' : IDL.Float64,
  'handTowels' : IDL.Float64,
  'faceTowels' : IDL.Float64,
});
export const Worker = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'isAdmin' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'addDispatchEntry' : IDL.Func(
      [TowelType, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addProductionEntry' : IDL.Func(
      [TowelType, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'adjustStock' : IDL.Func(
      [TowelType, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDispatchHistory' : IDL.Func([], [IDL.Vec(DispatchEntry)], ['query']),
  'getProductionHistory' : IDL.Func([], [IDL.Vec(ProductionEntry)], ['query']),
  'getStock' : IDL.Func([], [Stock], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'removeWorker' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setInitialStock' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TowelType = IDL.Variant({
    'bath' : IDL.Null,
    'face' : IDL.Null,
    'hand' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DispatchEntry = IDL.Record({
    'id' : IDL.Nat64,
    'destination' : IDL.Text,
    'date' : IDL.Text,
    'towelType' : TowelType,
    'quantityMeters' : IDL.Float64,
    'notes' : IDL.Text,
    'adminId' : IDL.Principal,
  });
  const ProductionEntry = IDL.Record({
    'id' : IDL.Nat64,
    'workerId' : IDL.Principal,
    'date' : IDL.Text,
    'towelType' : TowelType,
    'quantityMeters' : IDL.Float64,
    'notes' : IDL.Text,
    'workerName' : IDL.Text,
  });
  const Stock = IDL.Record({
    'bathTowels' : IDL.Float64,
    'handTowels' : IDL.Float64,
    'faceTowels' : IDL.Float64,
  });
  const Worker = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'isAdmin' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'addDispatchEntry' : IDL.Func(
        [TowelType, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addProductionEntry' : IDL.Func(
        [TowelType, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'adjustStock' : IDL.Func(
        [TowelType, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDispatchHistory' : IDL.Func([], [IDL.Vec(DispatchEntry)], ['query']),
    'getProductionHistory' : IDL.Func(
        [],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getStock' : IDL.Func([], [Stock], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'removeWorker' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setInitialStock' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };